import dbConnect from "@/lib/mongodb";
import { Resume } from "@/lib/models";
import { NextResponse } from "next/server";
import jwt from "jsonwebtoken";
import mongoose from "mongoose";

export async function POST(request) {
  try {
    await dbConnect();
    
    // Get token from cookie
    const token = request.cookies.get("auth_token")?.value;
    if (!token) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Decode token
    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    const userId = decoded.userId;

    const body = await request.json();
    const { id, title, data } = body;

    if (!title || !data) {
      return NextResponse.json({ error: "Title and Data are required" }, { status: 400 });
    }

    // Find or Create resume
    let resume = null;
    if (id) {
      resume = await Resume.findOne({ _id: id, userId: new mongoose.Types.ObjectId(userId) });
    } else {
      resume = await Resume.findOne({ userId: new mongoose.Types.ObjectId(userId), title });
    }

    if (resume) {
      resume.data = data;
      resume.updatedAt = Date.now();
      // If the existing resume has a null publicId, give it one now to fix the index error
      if (!resume.publicId) {
        resume.publicId = Math.random().toString(36).substring(2, 11) + Math.random().toString(36).substring(2, 11);
      }
    } else {
      resume = new Resume({
        userId: new mongoose.Types.ObjectId(userId),
        title,
        data,
        // publicId will be generated by the default value in the schema if we don't provide it,
        // but we'll provide it here just to be 100% sure.
        publicId: Math.random().toString(36).substring(2, 11) + Math.random().toString(36).substring(2, 11)
      });
    }
    
    // Explicitly tell Mongoose that 'data' has been modified
    // This is required for 'Object' or 'Mixed' types to ensure changes are saved
    resume.markModified('data');

    await resume.save();

    return NextResponse.json({ message: "Resume saved successfully", resume }, { status: 200 });
  } catch (error) {
    console.error("Error saving resume:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function GET(request) {
  try {
    await dbConnect();
    
    const token = request.cookies.get("auth_token")?.value;
    if (!token) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    const userId = decoded.userId;

    const { searchParams } = new URL(request.url);
    const id = searchParams.get("id");

    if (id) {
      const resume = await Resume.findOne({ _id: id, userId: new mongoose.Types.ObjectId(userId) });
      if (!resume) {
        return NextResponse.json({ error: "Resume not found" }, { status: 404 });
      }
      return NextResponse.json({ resume }, { status: 200 });
    }

    const resumes = await Resume.find({ userId: new mongoose.Types.ObjectId(userId) }).sort({ updatedAt: -1 });

    return NextResponse.json({ resumes }, { status: 200 });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

export async function DELETE(request) {
  try {
    await dbConnect();
    
    const token = request.cookies.get("auth_token")?.value;
    if (!token) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const decoded = jwt.verify(token, process.env.JWT_SECRET);
    const userId = decoded.userId;

    const { searchParams } = new URL(request.url);
    const resumeId = searchParams.get("id");

    if (!resumeId) {
      return NextResponse.json({ error: "Resume ID is required" }, { status: 400 });
    }

    const result = await Resume.findOneAndDelete({ _id: resumeId, userId: new mongoose.Types.ObjectId(userId) });

    if (!result) {
      return NextResponse.json({ error: "Resume not found or unauthorized" }, { status: 404 });
    }

    return NextResponse.json({ message: "Resume deleted successfully" }, { status: 200 });
  } catch (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
